import React from "react";
import { useUser } from "@auth0/nextjs-auth0/client";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import styles from "@/styles/Banco.module.css";
import RedirectLogin from "@/components/RedirectLogin";
import ProSidebar from "@/components/ProSidebar";
import Head from "next/head";

function BancoTalento() {
  const { user, error, isLoading } = useUser();
  console.log(user);

//   const userRoles = user?.[`${process.env.NEXT_PUBLIC_AUTH0_NAMESPACE}`] ?? [];

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  if (user && !user.email_verified) {
    return (
      <div>
        <RedirectLogin
          mensaje="Por favor verifica tu email antes de iniciar sesión. Redireccionandote al inicio en 5 segundos..."
        />
      </div>
    );
  }

  if (user) {
    return (
      user && (
        <div className={styles.wrapper}>
          <Head>
            <title>Banco de Talento | HR Hub</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
            <ProSidebar />
            <main className={styles.mainBanco}>
                
            </main>
        </div>
      )
    );
  }
}

export default BancoTalento;

export const getServerSideProps = withPageAuthRequired();
